### ISSUE TITLE
Some functions not working

### ISSUE THREAD

**Issue by ueffel** [ThaSiouL/Keypirinha-Package-Calc#1]
The bin() and hex() functions aren't working in your package (maybe more). The problem seems to be your presision enhancement. If the result from the simpleeval library isn't numeric (for bin() and hex() the result is a string), the formatting with presision throws the following exception in [Line 125](https://github.com/ThaSiouL/Keypirinha-Package-Calc/blob/master/src/calc.py#L125):
`Unknown format code 'g' for object of type 'str'`

Maybe you should check the `type` of the result before formatting and don't format for binary or hexadecimal strings.

**Comment by ThaSiouL** [comment]
Sorry this took so long (vacation last week) but it should work now. If not feel free to reopen the issue.
